/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PaymentPlansRouteImport } from './routes/payment-plans'
import { Route as PatientPortalRouteImport } from './routes/patient-portal'
import { Route as PatientFormsRouteImport } from './routes/patient-forms'
import { Route as PatientCheckinRouteImport } from './routes/patient-checkin'
import { Route as OurFamilyRouteImport } from './routes/our-family'
import { Route as OrthodonticsRouteImport } from './routes/orthodontics'
import { Route as ImplantsRouteImport } from './routes/implants'
import { Route as GeneralDentistryRouteImport } from './routes/general-dentistry'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CosmeticRouteImport } from './routes/cosmetic'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPlansRoute = PaymentPlansRouteImport.update({
  id: '/payment-plans',
  path: '/payment-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalRoute = PatientPortalRouteImport.update({
  id: '/patient-portal',
  path: '/patient-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientFormsRoute = PatientFormsRouteImport.update({
  id: '/patient-forms',
  path: '/patient-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientCheckinRoute = PatientCheckinRouteImport.update({
  id: '/patient-checkin',
  path: '/patient-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const OurFamilyRoute = OurFamilyRouteImport.update({
  id: '/our-family',
  path: '/our-family',
  getParentRoute: () => rootRouteImport,
} as any)
const OrthodonticsRoute = OrthodonticsRouteImport.update({
  id: '/orthodontics',
  path: '/orthodontics',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsRoute = ImplantsRouteImport.update({
  id: '/implants',
  path: '/implants',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralDentistryRoute = GeneralDentistryRouteImport.update({
  id: '/general-dentistry',
  path: '/general-dentistry',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticRoute = CosmeticRouteImport.update({
  id: '/cosmetic',
  path: '/cosmetic',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cosmetic': typeof CosmeticRoute
  '/gallery': typeof GalleryRoute
  '/general-dentistry': typeof GeneralDentistryRoute
  '/implants': typeof ImplantsRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/our-family': typeof OurFamilyRoute
  '/patient-checkin': typeof PatientCheckinRoute
  '/patient-forms': typeof PatientFormsRoute
  '/patient-portal': typeof PatientPortalRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cosmetic': typeof CosmeticRoute
  '/gallery': typeof GalleryRoute
  '/general-dentistry': typeof GeneralDentistryRoute
  '/implants': typeof ImplantsRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/our-family': typeof OurFamilyRoute
  '/patient-checkin': typeof PatientCheckinRoute
  '/patient-forms': typeof PatientFormsRoute
  '/patient-portal': typeof PatientPortalRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cosmetic': typeof CosmeticRoute
  '/gallery': typeof GalleryRoute
  '/general-dentistry': typeof GeneralDentistryRoute
  '/implants': typeof ImplantsRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/our-family': typeof OurFamilyRoute
  '/patient-checkin': typeof PatientCheckinRoute
  '/patient-forms': typeof PatientFormsRoute
  '/patient-portal': typeof PatientPortalRoute
  '/payment-plans': typeof PaymentPlansRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/contact'
    | '/cosmetic'
    | '/gallery'
    | '/general-dentistry'
    | '/implants'
    | '/orthodontics'
    | '/our-family'
    | '/patient-checkin'
    | '/patient-forms'
    | '/patient-portal'
    | '/payment-plans'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contact'
    | '/cosmetic'
    | '/gallery'
    | '/general-dentistry'
    | '/implants'
    | '/orthodontics'
    | '/our-family'
    | '/patient-checkin'
    | '/patient-forms'
    | '/patient-portal'
    | '/payment-plans'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/contact'
    | '/cosmetic'
    | '/gallery'
    | '/general-dentistry'
    | '/implants'
    | '/orthodontics'
    | '/our-family'
    | '/patient-checkin'
    | '/patient-forms'
    | '/patient-portal'
    | '/payment-plans'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CosmeticRoute: typeof CosmeticRoute
  GalleryRoute: typeof GalleryRoute
  GeneralDentistryRoute: typeof GeneralDentistryRoute
  ImplantsRoute: typeof ImplantsRoute
  OrthodonticsRoute: typeof OrthodonticsRoute
  OurFamilyRoute: typeof OurFamilyRoute
  PatientCheckinRoute: typeof PatientCheckinRoute
  PatientFormsRoute: typeof PatientFormsRoute
  PatientPortalRoute: typeof PatientPortalRoute
  PaymentPlansRoute: typeof PaymentPlansRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-plans': {
      id: '/payment-plans'
      path: '/payment-plans'
      fullPath: '/payment-plans'
      preLoaderRoute: typeof PaymentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal': {
      id: '/patient-portal'
      path: '/patient-portal'
      fullPath: '/patient-portal'
      preLoaderRoute: typeof PatientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-forms': {
      id: '/patient-forms'
      path: '/patient-forms'
      fullPath: '/patient-forms'
      preLoaderRoute: typeof PatientFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-checkin': {
      id: '/patient-checkin'
      path: '/patient-checkin'
      fullPath: '/patient-checkin'
      preLoaderRoute: typeof PatientCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-family': {
      id: '/our-family'
      path: '/our-family'
      fullPath: '/our-family'
      preLoaderRoute: typeof OurFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orthodontics': {
      id: '/orthodontics'
      path: '/orthodontics'
      fullPath: '/orthodontics'
      preLoaderRoute: typeof OrthodonticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants': {
      id: '/implants'
      path: '/implants'
      fullPath: '/implants'
      preLoaderRoute: typeof ImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-dentistry': {
      id: '/general-dentistry'
      path: '/general-dentistry'
      fullPath: '/general-dentistry'
      preLoaderRoute: typeof GeneralDentistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetic': {
      id: '/cosmetic'
      path: '/cosmetic'
      fullPath: '/cosmetic'
      preLoaderRoute: typeof CosmeticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CosmeticRoute: CosmeticRoute,
  GalleryRoute: GalleryRoute,
  GeneralDentistryRoute: GeneralDentistryRoute,
  ImplantsRoute: ImplantsRoute,
  OrthodonticsRoute: OrthodonticsRoute,
  OurFamilyRoute: OurFamilyRoute,
  PatientCheckinRoute: PatientCheckinRoute,
  PatientFormsRoute: PatientFormsRoute,
  PatientPortalRoute: PatientPortalRoute,
  PaymentPlansRoute: PaymentPlansRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
